theme: jekyll-theme-minimal
title: Data Science Portfolio
author: Chandramouli Yalamanchili

navbar-links:
  About Me: "aboutme"
  
  
social-network-links:
  github: chandu85
  linkedin: chandu85

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
